-- PostgreSQL database dump for books table

-- Create the books table
CREATE TABLE public.books (
    id bigint NOT NULL,
    author character varying(255),
    rating integer,
    title character varying(255),
    year integer
);

-- Set the owner of the table
ALTER TABLE public.books OWNER TO titasstuopis;

-- Create the sequence for the id
ALTER TABLE public.books ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.books_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Copy data into the books table
COPY public.books (id, author, rating, title, year) FROM stdin;
2	George Orwell	\N	1984	1949
3	F. Scott Fitzgerald	\N	The Great Gatsby	1925
4	Herman Melville	\N	Moby Dick	1851
5	Leo Tolstoy	\N	War and Peace	1869
6	Jane Austen	\N	Pride and Prejudice	1813
7	J.D. Salinger	\N	The Catcher in the Rye	1951
8	J.R.R. Tolkien	\N	The Lord of the Rings	1954
9	J.R.R. Tolkien	\N	The Hobbit	1937
10	Ray Bradbury	\N	Fahrenheit 451	1953
11	Aldous Huxley	\N	Brave New World	1932
12	Oscar Wilde	\N	The Picture of Dorian Gray	1890
13	Charlotte Brontë	\N	Jane Eyre	1847
14	Homer	\N	The Odyssey	-800
15	Dante Alighieri	\N	The Divine Comedy	1320
16	C.S. Lewis	\N	The Chronicles of Narnia	1950
17	Joseph Heller	\N	Catch-22	1961
18	Sylvia Plath	\N	The Bell Jar	1963
19	George Orwell	\N	Animal Farm	1945
20	Victor Hugo	\N	Les Misérables	1862
21	Paulo Coelho	\N	The Alchemist	1988
22	Cormac McCarthy	\N	The Road	2006
23	Khaled Hosseini	\N	The Kite Runner	2003
24	John Green	\N	The Fault in Our Stars	2012
25	Yann Martel	\N	Life of Pi	2001
26	Markus Zusak	\N	The Book Thief	2005
27	J.R.R. Tolkien	\N	The Hobbit	1937
28	Stephen King	\N	The Shining	1977
29	Suzanne Collins	\N	The Hunger Games	2008
30	Margaret Mitchell	\N	Gone with the Wind	1936
31	J.D. Salinger	\N	The Catcher in the Rye	1951
32	Emily Brontë	\N	Wuthering Heights	1847
33	John Steinbeck	\N	The Grapes of Wrath	1939
34	Ernest Hemingway	\N	The Old Man and the Sea	1952
35	Bram Stoker	\N	Dracula	1897
36	Frances Hodgson Burnett	\N	The Secret Garden	1911
\.

-- Set the sequence value
SELECT pg_catalog.setval('public.books_id_seq', 37, true);

-- Add primary key constraint
ALTER TABLE ONLY public.books
    ADD CONSTRAINT books_pkey PRIMARY KEY (id);
